# Travis CI config for Enayet Shell
# Tests if shell can build properly
sudo: false
language: rust
cache: cargo

# create test coverage data
before_script: |
  PKGNAME="ensh" # must match with cargo.toml
  LOCAL="~/.local" # install here to avoid `sudo`
  export PATH=$LOCAL/bin:$PATH

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libbfd-dev # required for `--verify`

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
  cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && make &&
  make install && cd ../.. &&

  kcov --verify \
  --coveralls-id=$TRAVIS_JOB_ID \
  --exclude-pattern=/.cargo \
  target/kcov target/debug/$PKGNAME-*

