[package]
name = "ensh"
version = "0.4.2"
authors = ["Afnan Enayet <me@afnan.io>"]

[dependencies]

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "ensh"
path = "src/main.rs"
doc = false

[lib]
name = "enshlib"
path = "src/lib.rs"
