[package]
name = "ensh"
version = "0.4.0"
authors = ["Afnan Enayet <me@afnan.io>"]

[profile.release]
lto = true
panic = 'abort'

[lib]
name = "ensh"
path = "src/lib.rs"

[[bin]]
name = "ensh_bin"
path = "src/main.rs"

